### ISSUE TITLE
数据库不能正常连接

### ISSUE THREAD

**Issue by nb5p** [qishibo/alpine-lnmp#1]
弄了一晚上，我以为是自己写的php或dockerfile有问题，一直出错。这才发现原来你的这个镜像的mysql就是摆设，无法连接。希望可以更新一下。

## 测试过程
将`index.php`修改为以下内容，会报错`Connection refused`

```
<?php
$a = new mysqli("127.0.0.1", "root", "root");
if ($a->connect_error) {
	die($a->connect_error);
}
echo "chenggong";
```

**Comment by qishibo** [comment]
you sure?
![image](https://user-images.githubusercontent.com/5136418/58389446-37eb6b80-805d-11e9-80fd-9c12d5523ac3.png)
![image](https://user-images.githubusercontent.com/5136418/58389448-3f127980-805d-11e9-920e-321ddf81a5c8.png)

贴一下操作流程，包括镜像怎么跑起来的

或者你可以先将“127.0.0.1”改为localhost试试

**Comment by nb5p** [comment]
和README里一样
```
 9086  git clone git@github.com:qishibo/alpine-lnmp.git
 9088  cd alpine-lnmp
 9090  vim index.php
 9092  docker build -t alpine-lnmp:latest .
 9093  docker run -itd -p80:80 -p3306:3306 --name alpine-lnmp alpine-lnmp:latest
# 这里试了输出 Connection refused，尝试使用no-cache
 9096  docker build --no-cache -t alpine-lnmp:latest .
 9098  docker stop alpine-lnmp
 9100  docker rm alpine-lnmp
 9101  docker run -itd -p80:80 -p3306:3306 --name alpine-lnmp alpine-lnmp:latest
# 同样的结果
```
<img width="383" alt="屏幕快照 2019-05-27 09 46 03" src="https://user-images.githubusercontent.com/2098464/58390533-46895100-8064-11e9-8237-81859bca04d6.png">

上面是从history里粘出来的，删了几行ls和输入错误的命令

**Comment by qishibo** [comment]
或者你可以先将“127.0.0.1”改为localhost试试
这个试过了么

**Comment by nb5p** [comment]
试了，成功了。感谢

还有问题，就是怎么导入sql文件到数据库。
我希望在编译好就是导入的而不是使用`docker exec -i alpine-lnmp mysql -uroot -proot vuldata < vuldata.sql`

我在`PrivilegeUser`中添加了`CREATE DATABASE vuldata`
在`mysqld_safe`后添加了`mysql -uroot -proot vuldata < /root/vuldata.sql`导入不成功

**Comment by qishibo** [comment]
跑起来之后外部用个mysql连接工具连一下，导进去，没必要放到镜像里

**Comment by nb5p** [comment]
确实需要放到镜像中，已经解决了。需要sleep几秒再导入

**Comment by qishibo** [comment]
恩 那是mysql在初始化
